FileVersion = 1
Dependencies = {corlib = "*", CommanderFX = "*"}

[Project]
Name = "CommanderFX.Test"
TargetType = "BeefTest"
StartupObject = "CommanderFX.Test.Program"

[Configs.Debug.Win64]
BuildKind = "Test"

[[Configs.Debug.Win64.DistinctOptions]]
Filter = ""
BfOptimizationLevel = "OgPlus"
EmitDebugInfo = "Yes"
